import GenerationCardinality

#print axioms GenerationCardinality.cardinality_endpoint_certificate_closure
#print axioms GenerationCardinality.generation_role_certificate_closure
#print axioms GenerationCardinality.open_arena_lifting_of_cp_holonomy_carrier
#print axioms GenerationCardinality.no_generation_by_presentation
#print axioms GenerationCardinality.no_selector_theorem
#print axioms GenerationCardinality.pairwise_completeness_is_forced
#print axioms GenerationCardinality.complete_graph_normal_form
#print axioms GenerationCardinality.first_exact_circuit_rank
#print axioms GenerationCardinality.cycle_quotient_theorem
#print axioms GenerationCardinality.role_incidence_liveness
#print axioms GenerationCardinality.primitive_carrier_nonvacuity
#print axioms GenerationCardinality.rank_one_primitive_target_theorem
#print axioms GenerationCardinality.rank_matching_condition
#print axioms GenerationCardinality.lower_cardinality_eliminators
#print axioms GenerationCardinality.three_role_positive_certificate
#print axioms GenerationCardinality.no_higher_generation_closure
#print axioms GenerationCardinality.generation_cardinality_as_forced_role_occupancy_endpoint
#print axioms GenerationCardinality.closed_generation_certificate_iff_three
#print axioms GenerationCardinality.arc_handoff
#print axioms GenerationCardinality.fourth_generation_branch
#print axioms GenerationCardinality.reality_contact_for_generation_cardinality
#print axioms GenerationCardinality.generation_cardinality_paper_recognized
#print axioms GenerationCardinality.generation_cardinality_scope_boundary
#print axioms GenerationCardinality.a_plus_inventory_complete
